FitnessClubApp.Web/Areas/Management/Controllers/MainPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FitnessClubApp.Service;
using FitnessClubApp.Web.Areas.Management.ViewModels;

namespace FitnessClubApp.Web.Areas.Management.Controllers
{
    [Authorize(Roles = "Trainer,Receptionist,Manager,Admin")]
    public class MainPanelController : Controller
    {
        private readonly IStatisticService statisticService;

        public MainPanelController(IStatisticService statisticService)
        {
            this.statisticService = statisticService;
        }

        public ActionResult Index()
        {
            var mainPanelData = new DisplayMainPanelData
            {
                DailyRegisteredEntries = statisticService.GetDailyRegisteredEntries(),
                DailyUsersInEvents = statisticService.GetDailyUsersInEvents(),
                DailyRegisteredAccounts = statisticService.GetDailyRegisteredAccounts(),
                DailyTransactions = statisticService.GetDailyAmountOfSales(),
                MonthlyRegisteredAccounts = statisticService.GetMonthlyRegisteredAccounts(),
                MonthlyRegisteredEntries = statisticService.GetMonthlyRegisteredEntries(),
                MonthlyTransactions = statisticService.GetMonthlyAmountOfSales(),
                MonthlyUsersInEvents = statisticService.GetMonthlyUsersInEvents(),
                AnnualRegisteredAccounts = statisticService.GetAnnualRegisteredAccounts(),
                AnnualRegisteredEntries = statisticService.GetAnnualRegisteredEntries(),
                AnnualTransactions = statisticService.GetAnnualAmountOfSales(),
                AnnualUsersInEvents = statisticService.GetAnnualUsersInEvents(),
                AllRegisteredAccounts = statisticService.GetAllRegisteredAccounts(),
                AllRegisteredEntries = statisticService.GetAllRegisteredEntries(),
                AllTransactions = statisticService.GetAllAmountOfSales(),
                AllUsersInEvents = statisticService.GetAllUsersInEvents(),
                AmountOfEquipments = statisticService.GetAmountOfEquipments(),
                AmountOfManagers = statisticService.GetAmountOfManagers(),
                AmountOfReceptionists = statisticService.GetAmountOfReceptionists(),
                AmountOfRooms = statisticService.GetAmountOfRooms(),
                AmountOfTrainers = statisticService.GetAmountOfTrainers(),
                AmountOfTrainings = statisticService.GetAmountOfTrainings(),
                AmountOfSubscriptions = statisticService.GetAmountOfSubscriptions()
            };

            return View(mainPanelData);
        }
    }
}

FitnessClubApp.Web/Areas/Membership/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using FitnessClubApp.Model;
using FitnessClubApp.Service;
using FitnessClubApp.Web.Areas.Membership.ViewModels;
using FitnessClubApp.Web.Extensions.Alerts;
using Microsoft.AspNet.Identity;

namespace FitnessClubApp.Web.Areas.Membership.Controllers
{
    [Authorize(Roles = "User")]
    public class StoreController : Controller
    {
        private readonly IPurchasedSubscriptionService purchasedSubscriptionService;
        private readonly ISubscriptionService subscriptionService;
        private readonly IUserService userService;
        private readonly IEmailService emailService;

        public StoreController(ISubscriptionService subscriptionService, IUserService userService, IPurchasedSubscriptionService purchasedSubscriptionService, IEmailService emailService)
        {
            this.purchasedSubscriptionService = purchasedSubscriptionService;
            this.subscriptionService = subscriptionService;
            this.userService = userService;
            this.emailService = emailService;
        } 

        [AllowAnonymous]
        public ActionResult Choose()
        {
            var subscriptions = subscriptionService.GetSortedSubscriptions();
            return View(subscriptions);
        }
        
        [HttpGet]
        public ActionResult Checkout(int subscriptionID)
        {
            var user = userService.GetUser(User.Identity.GetUserName());
            if (user == null)
                return RedirectToAction("Choose")
                    .WithDanger("Nie możesz przejść do kasy.", "Musisz być zalogowanym do konta.");

            var subscription = subscriptionService.GetSubscription(subscriptionID);
            if (subscription == null)
                return RedirectToAction("Choose")
                    .WithDanger("Nie możesz przejść do kasy.", "Wybrałeś nieistniejącą subskrypcję.");

            var subscriptionOrderFormViewModel = new SubscriptionOrderFormViewModel
            {
                User = user,
                UserID = user.UserID,
                Subscription = subscription,
                SubscriptionID = subscription.SubscriptionID
            };

            var lastPurchasedSubscription = purchasedSubscriptionService.GetLastUserPurchasedSubscription(user.UserID);
            if (lastPurchasedSubscription != null)
            {
                subscriptionOrderFormViewModel = Mapper.Map(lastPurchasedSubscription, subscriptionOrderFormViewModel);
            }

            return View(subscriptionOrderFormViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Checkout(SubscriptionOrderFormViewModel subscriptionOrderFormView)
        {
            var user = userService.GetUser(User.Identity.GetUserName());
            if (user == null)
                return RedirectToAction("Choose")
                    .WithDanger("Nie możesz przejść do podsumowania.", "Musisz być zalogowanym do konta.");

            var subscription = subscriptionService.GetSubscription(subscriptionOrderFormView.SubscriptionID);
            if (subscription == null)
                return RedirectToAction("Choose")
                    .WithDanger("Nie możesz przejść do podsumowania.", "Wybrałeś nieistniejącą subskrypcję.");

            if (user.UserID != subscriptionOrderFormView.UserID)
                return RedirectToAction("Choose")
                    .WithDanger("Nie możesz przejść do podsumowania.", "Chcesz przypisać subskrypcję do użytkownika, na którym nie jesteś obecnie zalogowanym.");

            subscriptionOrderFormView.Subscription = subscription;
            subscriptionOrderFormView.User = user;

            if (!ModelState.IsValid)
                return View(subscriptionOrderFormView);

            var purchasedSubscriptionExists =
                purchasedSubscriptionService.PurchasedSubscriptionExists(user.UserID,
                    subscriptionOrderFormView.StartDate, subscription.Days);
            if (purchasedSubscriptionExists)
            {
                ModelState.AddModelError("StartDate", "Kupiłeś już subskrypcję w wybranych datach");
                return View(subscriptionOrderFormView);
            }

            Session["subscriptionOrdered"] = subscriptionOrderFormView;

            return RedirectToAction("Summary");
        }

        [HttpGet]
        public ActionResult Summary()
        {
            var subscriptionOrdered = Session["subscriptionOrdered"];

            if (subscriptionOrdered == null || subscriptionOrdered.GetType() != typeof(SubscriptionOrderFormViewModel))
                return RedirectToAction("Choose")
                    .WithDanger("Nie możesz przejść do podsumowania.", "Nie złożyłeś dyspozycji zakupu subskrypcji."); 

            return View(subscriptionOrdered);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Confirm()
        {
            var subscriptionOrderedViewModel = Session["subscriptionOrdered"];

            if (subscriptionOrderedViewModel == null || subscriptionOrderedViewModel.GetType() != typeof(SubscriptionOrderFormViewModel))
                return RedirectToAction("Choose")
                    .WithDanger("Nie możesz przejść do podsumowania.", "Nie złożyłeś dyspozycji zakupu subskrypcji.");

            var purchasedSubscription =
                Mapper.Map<SubscriptionOrderFormViewModel, PurchasedSubscription>(subscriptionOrderedViewModel as SubscriptionOrderFormViewModel);

            purchasedSubscription.User = null;
            purchasedSubscriptionService.CreatePurchasedSubscription(purchasedSubscription);
            purchasedSubscriptionService.SavePurchasedSubscription();

            var user = (subscriptionOrderedViewModel as SubscriptionOrderFormViewModel)?.User;

            Session["subscriptionOrdered"] = null;

            emailService.SendConfirmationPurchaseSubscription(user, purchasedSubscription);

            return RedirectToAction("Confirmation", new { purchasedSubscriptionID = purchasedSubscription.PurchasedSubscriptionID });
        }

        [HttpGet]
        public ActionResult Confirmation(int purchasedSubscriptionID)
        {
            var purchasedSubscription = purchasedSubscriptionService.GetPurchasedSubscription(purchasedSubscriptionID);

            if (purchasedSubscription == null)
                return RedirectToAction("Index", "Home").WithDanger("Potwierdzenie nie zostanie wygenerowane.", "Zły parametr do utworzenia potwierdzenia.");

            var user = userService.GetUser(purchasedSubscription.UserID);

            if (user.Email != User.Identity.GetUserName())
                return RedirectToAction("Index", "Home").WithDanger("Potwierdzenie nie zostanie wygenerowane.", "Zalogowany użytkownik nie ma takich uprawnień.");

            return View(purchasedSubscription);
        }
    }
}

FitnessClubApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FitnessClubApp</title>
    <link rel="shortcut icon" type="image/ico" href="~/Images/favicon.ico">
    <link href="~/Content/gijgo/combined/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/dashboard.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fontawesome/all.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/tempusdominus-bootstrap-4.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <link href="~/Content/carousel.css" rel="stylesheet" />
    <link href="~/Content/fullcalendar.min.css" rel="stylesheet" />
    <link href="~/Content/scheduler.min.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/umd/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/respond.js"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/moment-with-locales.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/tempusdominus-bootstrap-4.min.js"></script>
    <script src="~/Scripts/Chart.js"></script>
    <script src="~/Scripts/fullcalendar.js"></script>
    <script src="~/Scripts/scheduler.min.js"></script>
    <script src="~/Scripts/locale-all.js"></script>
    <script src="~/Scripts/jspdf.debug.js"></script>
    <script src="~/Scripts/html2canvas.js"></script>
</head>
<body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow d-block">
        <div class="d-flex">
            <a class="app-logo navbar-brand flex-grow-1 m-0" href="@Url.Action("Index", "Home", new { area = string.Empty })"><i class="fas fa-dumbbell px-3 align-middle"></i><span class="align-middle">FitnessClubApp</span></a>
            @if (User.Identity.IsAuthenticated)
            {
                Html.RenderAction("GetNavbarItems", "Home", new {area = string.Empty});
            }
            @Html.Partial("_LoginPartial")
        </div>
    </nav>

    <div>

        @Html.Partial("_StatusMessages")

        @RenderBody()

        @if (string.IsNullOrEmpty(ViewContext.RouteData.DataTokens["area"]?.ToString()) || ViewContext.RouteData.DataTokens["area"].ToString() == "Membership")
        {
            <hr />

            <footer class="text-center my-4">
                <span>&copy; @DateTime.Now.Year FitnessClubApp</span>
            </footer>
        }
    </div>


    @RenderSection("scripts", required: false)

    <script>
        var date = new Date();
        date.setDate(date.getDate() + 30);

        $('#date-of-birth-picker').datetimepicker({
            locale: 'pl',
            format: 'L',
            useCurrent: false,
            maxDate: new Date().setHours(0, 0, 0, 0),
            minDate: '1900-01-01',
            viewMode: 'years'
        });

        $('#subscription-start-date-picker').datetimepicker({
            locale: 'pl',
            format: 'L',
            useCurrent: false,
            maxDate: date.setHours(0, 0, 0, 0),
            minDate: new Date().setHours(0, 0, 0, 0)
        });

        $.validator.addMethod('checkboxischecked', function (value, element) {
            return $(element).is(":checked");
        });

        $.validator.unobtrusive.adapters.add('checkboxischecked', [], function (options) {
            options.messages['checkboxischecked'] = options.message;
            options.rules['checkboxischecked'] = options.params;
        });
    </script>

</body>
</html>

FitnessClubApp.Web/Views/Shared/_NavbarItems.cshtml
@using FitnessClubApp.Web.Extensions.HtmlHelpers
@model object

@if (User.IsInRole("User"))
{
    <div class="navbar-brand-color w-100 d-flex">
        <ul class="navbar-nav py-2 px-3">
            <li class="nav-item text-nowrap">
                @Html.ActionLink("Kup karnet", "Choose", "Store", routeValues: new { area = "Membership" }, htmlAttributes: new { @class = $"nav-link { Html.IsSelected("Choose,Checkout,Confirmation,Summary", "Store") }" })
            </li>
        </ul>
        <ul class="navbar-nav py-2 px-3">
            <li class="nav-item text-nowrap">
                @Html.ActionLink("Historia transakcji", "History", "PurchasedSubscription", routeValues: new { area = "Membership" }, htmlAttributes: new { @class = $"nav-link { Html.IsSelected("History", "PurchasedSubscription") }" })
            </li>
        </ul>
        <ul class="navbar-nav py-2 px-3">
            <li class="nav-item text-nowrap">
                @Html.ActionLink("Rezerwacja zajęć", "Index", "SeatReservation", routeValues: new { area = "Membership" }, htmlAttributes: new { @class = $"nav-link { Html.IsSelected("Index", "SeatReservation") }" })
            </li>
        </ul>
        <ul class="navbar-nav py-2 px-3">
            <li class="nav-item text-nowrap">
                @Html.ActionLink("Historia wejść", "Index", "EntryHistory", routeValues: new { area = "Membership" }, htmlAttributes: new { @class = $"nav-link { Html.IsSelected("Index", "EntryHistory") }" })
            </li>
        </ul>
        <ul class="navbar-nav py-2 px-3">
            <li class="nav-item text-nowrap">
                @Html.ActionLink("Dyżury trenerów", "Index", "WorkShiftsTrainers", routeValues: new { area = "Membership" }, htmlAttributes: new { @class = $"nav-link { Html.IsSelected("Index", "WorkShiftsTrainers") }" })
            </li>
        </ul>
        @{ Html.RenderAction("GetSubscriptionStatus", "Home", new { area = string.Empty }); }
    </div>
}
else if (User.Identity.IsAuthenticated)
{
    <div class="navbar-brand-color w-100 d-flex">
        <ul class="navbar-nav py-2 px-3">
            <li class="nav-item text-nowrap">
                @Html.ActionLink("Panel administracyjny", "Index", "MainPanel", routeValues: new { area = "Management" }, htmlAttributes: new { @class = $"nav-link { Html.IsSelected("*", "*", "Management") }" })
            </li>
        </ul>
    </div>
}

FitnessClubApp.Web/Views/Shared/_StatusMessages.cshtml
@{
    var type = (string)TempData["_alert.type"];
    var title = (string)TempData["_alert.title"];
    var body = (string)TempData["_alert.body"];
}

@if (!string.IsNullOrEmpty(type))
{
<div class="alert-content alert alert-@type alert-dismissible fade show" role="alert">
    <strong>@title</strong> @Html.Raw(body)

    <button type="button" class="close pt-2" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
}

FitnessClubApp.Web/Views/Shared/_SubscriptionStatus.cshtml
@model object

<ul class="navbar-nav ml-auto">
    <li class="nav-item text-nowrap" style="padding-top: 13px">
        <i class="fas fa-lg @(((bool?)Model).Value ? "fa-check-circle text-success" : "fa-times-circle text-danger") nav-link"></i>
    </li>
</ul>
<ul class="navbar-nav py-2 pr-3 pl-2">
    <li class="nav-item text-nowrap">
        <span class="nav-link active">@(((bool?)Model).Value ? "Aktywny subskrybent" : "Nieaktywny subskrybent")</span>
    </li>
</ul>