FitnessClubApp.Web/Areas/Membership/Controllers/PurchasedSubscriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using FitnessClubApp.Model;
using FitnessClubApp.Service;
using FitnessClubApp.Web.Areas.Management.ViewModels;
using FitnessClubApp.Web.Extensions.Alerts;

namespace FitnessClubApp.Web.Areas.Membership.Controllers
{
    [Authorize(Roles = "User")]
    public class PurchasedSubscriptionController : Controller
    {
        private readonly IPurchasedSubscriptionService purchasedSubscriptionService;
        private readonly IUserService userService;

        public PurchasedSubscriptionController(IPurchasedSubscriptionService purchasedSubscriptionService, IUserService userService)
        {
            this.purchasedSubscriptionService = purchasedSubscriptionService;
            this.userService = userService;
        }

        public ActionResult History()
        {
            var activePurchasedSubscription = purchasedSubscriptionService.GetActiveUserSubscription(User.Identity.Name);

            return View(activePurchasedSubscription);
        }

        public JsonResult GetTransactionHistory(int? page, int? limit)
        {
            List<DisplayTransactionViewModel> records;
            int total;

            var user = userService.GetUser(User.Identity.Name);

            var purchasedSubscriptions = purchasedSubscriptionService.GetUserPurchasedSubscriptions(user);

            var query = Mapper.Map<IEnumerable<PurchasedSubscription>, IEnumerable<DisplayTransactionViewModel>>(purchasedSubscriptions);

            query = query.OrderByDescending(q => q.OrderDate);

            total = query.Count();
            if (page.HasValue && limit.HasValue)
            {
                int start = (page.Value - 1) * limit.Value;
                records = query.Skip(start).Take(limit.Value).ToList();
            }
            else
            {
                records = query.ToList();
            }

            return Json(new { records, total }, JsonRequestBehavior.AllowGet);
        }
    }
}

FitnessClubApp.Web/Areas/Membership/Views/PurchasedSubscription/History.cshtml
@model FitnessClubApp.Model.PurchasedSubscription

@{
    ViewBag.Title = "Historia transakcji";
}

<script src="~/Scripts/gijgo/combined/gijgo.js" type="text/javascript"></script>

<div class="view-content">
    <div class="d-flex">
        <div>
            <h2 class="d-inline">Historia transakcji</h2>
        </div>
        <div class="ml-auto mt-auto">
            <i class="fas @(Model != null ? "fa-check-circle text-success" : "fa-times-circle text-danger") fa-lg"></i>
            <h5 class="d-inline ml-1"><small>@(Model != null ? $"Aktywny subskrybent (obecna subskrypcja zakończy się {Model.EndDate:dd.MM.yyyy})" : "Nieaktywny subskrybent")</small></h5>
        </div>
    </div>
    <hr />

    <div>
        <table id="grid"></table>
    </div>

    <div id="dialogDetail" style="display: none">
        <label>Data zamówienia</label>
        <strong id="OrderDate"></strong>
        <hr />
        <label>Nazwa subskrypcji</label>
        <strong id="SubscriptionName"></strong>
        <br />
        <label>Cena</label>
        <strong id="Price"></strong>
        <br />
        <label>Data rozpoczęcia</label>
        <strong id="StartDate"></strong>
        <br />
        <label>Data zakończenia</label>
        <strong id="EndDate"></strong>
        <hr />
        <label>Dane zamawiającego</label>
        <br />
        <strong id="PurcharserPersonalData"></strong>
        <br />
        <strong id="StreetAddress"></strong>
        <br />
        <strong id="ZipCodeAndCity"></strong>
    </div>

    <div class="py-3"></div>
</div>

<script type="text/javascript">
    var grid, dialogDetail;

        function Detail(e) {
            $('#SubscriptionName').text(e.data.record.SubscriptionName);
            $('#Price').text(e.data.record.Price);
            $('#OrderDate').text(e.data.record.OrderDate.toString('dd.mm.yyyy'));
            $('#StartDate').text(e.data.record.StartDate.toString('dd.mm.yyyy'));
            $('#EndDate').text(e.data.record.EndDate.toString('dd.mm.yyyy'));
            $('#PurcharserPersonalData').text(e.data.record.PurcharserPersonalData);
            $('#StreetAddress').text(e.data.record.StreetAddress);
            $('#ZipCodeAndCity').text(e.data.record.ZipCode + ' ' + e.data.record.City);
            $('#SubscriberPersonalData').text(e.data.record.SubscriberPersonalData);
            dialogDetail.open('Szczegóły transakcji ID ' + e.data.id);
        }

        $(document).ready(function () {
            grid = $('#grid').grid({
                primaryKey: 'PurchasedSubscriptionID',
                dataSource: '@Url.Action("GetTransactionHistory", "PurchasedSubscription", new { area = "Membership" })',
                uiLibrary: 'bootstrap4',
                columns: [
                    { field: 'PurchasedSubscriptionID', width: 70, title: 'ID', align: 'center' },
                    { field: 'OrderDate', title: 'Data zamówienia', type: 'date', format: 'dd.mm.yyyy HH:MM' },
                    { field: 'StartDate', type: 'date', format: 'dd.mm.yyyy', title: 'Data rozpoczęcia' },
                    { field: 'EndDate', type: 'date', format: 'dd.mm.yyyy', title: 'Data zakończenia' },
                    { field: 'SubscriptionName', title: 'Subskrypcja' },
                    { field: 'Price', title: 'Cena' },
                    { field: 'Shipment', title: 'Wysyłka', width: 90, type: 'checkbox', align: 'center' },
                    { field: 'Paid', title: 'Opłacone', width: 120, type: 'checkbox', align: 'center' },
                    { field: 'Complete', title: 'Zrealizowane', width: 120, type: 'checkbox', align: 'center' },
                    { title: '', align: 'center', field: 'Detail', width: 50, type: 'icon', icon: 'fas fa-info-circle fa-lg', tooltip: 'Zobacz szczegóły', events: { 'click': Detail } },
                ]
            });

            dialogDetail = $('#dialogDetail').dialog({
                autoOpen: false,
                resizable: false,
                modal: true,
                width: 360
            });
        });
</script>