FitnessClubApp.Web/Areas/Management/Controllers/EquipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using FitnessClubApp.Model;
using FitnessClubApp.Service;
using FitnessClubApp.Web.Areas.Management.ViewModels;

namespace FitnessClubApp.Web.Areas.Management.Controllers
{
    [Authorize(Roles = "Manager,Admin")]
    public class EquipmentController : Controller
    {
        private readonly IResourceService resourceService;

        public EquipmentController(IResourceService resourceService)
        {
            this.resourceService = resourceService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetEquipments(int? page, int? limit, string sortBy, string direction, string brand, string name)
        {
            List<DisplayEquipmentViewModel> records;
            int total;

            var equipments = resourceService.GetEquipments();
            var query = Mapper.Map<IEnumerable<Equipment>, IEnumerable<DisplayEquipmentViewModel>>(equipments);

            if (!string.IsNullOrWhiteSpace(name))
            {
                query = query.Where(q => q.Name.ToLower().Trim().Contains(name.ToLower().Trim()));
            }

            if (!string.IsNullOrWhiteSpace(brand))
            {
                query = query.Where(q => q.Brand.ToLower().Trim().Contains(brand.ToLower().Trim()));
            }

            if (!string.IsNullOrEmpty(sortBy) && !string.IsNullOrEmpty(direction))
            {
                if (direction.Trim().ToLower() == "asc")
                {
                    switch (sortBy)
                    {
                        case "Brand":
                            query = query.OrderBy(q => q.Brand);
                            break;
                        case "Name":
                            query = query.OrderBy(q => q.Name);
                            break;
                    }
                }
                else
                {
                    switch (sortBy)
                    {
                        case "Brand":
                            query = query.OrderByDescending(q => q.Brand);
                            break;
                        case "Name":
                            query = query.OrderByDescending(q => q.Name);
                            break;
                    }
                }
            }
            else
            {
                query = query.OrderBy(q => q.Name);
            }

            total = query.Count();
            if (page.HasValue && limit.HasValue)
            {
                int start = (page.Value - 1) * limit.Value;
                records = query.Skip(start).Take(limit.Value).ToList();
            }
            else
            {
                records = query.ToList();
            }

            return Json(new { records, total }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AddEquipment()
        {
            return PartialView("_AddEquipmentForm");
        }

        [HttpGet]
        public ActionResult EditEquipment(int equipmentID)
        {
            var equipment = resourceService.GetEquipment(equipmentID);

            if (equipment == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var equipmentFormViewModel = Mapper.Map<Equipment, EquipmentFormViewModel>(equipment);

            return PartialView("_EditEquipmentForm", equipmentFormViewModel);
        }

        [HttpGet]
        public ActionResult RemoveEquipment(int equipmentID)
        {
            var equipment = resourceService.GetEquipment(equipmentID);

            if (equipment == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return PartialView("_ConfirmationRemoveEquipment", equipment);
        }

        [HttpPost]
        public ActionResult AddEquipment(EquipmentFormViewModel equipmentFormViewModel)
        {
            if (!ModelState.IsValid)
            {
                Response.StatusCode = HttpStatusCode.BadRequest.GetHashCode();
                return PartialView("_AddEquipmentForm", equipmentFormViewModel);
            }
                
            var equipment = Mapper.Map<EquipmentFormViewModel, Equipment>(equipmentFormViewModel);

            var equipmentExists = resourceService.EquipmentExists(equipment);
            if (equipmentExists)
            {
                ModelState.AddModelError("Name", "Istnieje już sprzęt o podanej nazwie i marce");
                ModelState.AddModelError("Brand", "Istnieje już sprzęt o podanej nazwie i marce");

                Response.StatusCode = HttpStatusCode.BadRequest.GetHashCode();
                return PartialView("_AddEquipmentForm", equipmentFormViewModel);
            }

            resourceService.CreateEquipment(equipment);
            resourceService.SaveEquipment();

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        public ActionResult EditEquipment(EquipmentFormViewModel equipmentFormViewModel)
        {
            if (!ModelState.IsValid)
            {
                Response.StatusCode = HttpStatusCode.BadRequest.GetHashCode();
                return PartialView("_EditEquipmentForm", equipmentFormViewModel);
            }

            var equipment = Mapper.Map<EquipmentFormViewModel, Equipment>(equipmentFormViewModel);

            var equipmentExists = resourceService.EquipmentExists(equipment);
            if (equipmentExists)
            {
                ModelState.AddModelError("Name", "Istnieje już sprzęt o podanej nazwie i marce");
                ModelState.AddModelError("Brand", "Istnieje już sprzęt o podanej nazwie i marce");

                Response.StatusCode = HttpStatusCode.BadRequest.GetHashCode();
                return PartialView("_EditEquipmentForm", equipmentFormViewModel);
            }

            resourceService.EditEquipment(equipment);
            resourceService.SaveEquipment();

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        public ActionResult ConfirmationRemoveEquipment(int equipmentID)
        {
            var equipment = resourceService.GetEquipment(equipmentID);

            if (equipment == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            resourceService.RemoveEquipment(equipment);
            resourceService.SaveEquipment();

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
    }
}

FitnessClubApp.Web/Areas/Management/Views/Equipment/Index.cshtml
@{
    ViewBag.Title = "Zarządzanie - Sprzęt";
}

<script src="~/Scripts/gijgo/combined/gijgo.js" type="text/javascript"></script>

<h2>Sprzęt
    @Ajax.ActionLink(
        linkText: " ",
        actionName: "AddEquipment",
        routeValues: new {},
        ajaxOptions: new AjaxOptions
        {
            HttpMethod = "GET",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "modal",
            OnSuccess = "$('#modalEquipmentForm').modal({backdrop: 'static', keyboard: false}); $.validator.unobtrusive.parse(\"#equipmentForm\");"
        },
        htmlAttributes: new {@class = "btn btn-icon fa-lg fas fa-plus-square text-success float-right" })
</h2>

<hr />

<div class="container-fluid">
    <div class="row">
        <form class="form-inline w-100">
            <div class="col">
                <input id="txtName" type="text" placeholder="Nazwa..." class="w-100 form-control mb-2 mr-sm-2 mb-sm-0" />
            </div>
            <div class="col">
                <input id="txtBrand" type="text" placeholder="Marka..." class="w-100 form-control mb-2 mr-sm-2 mb-sm-0" />
            </div>
            <div class="col-auto h-100">
                <button id="btnSearch" type="button" class="h-100 btn btn-light btn-lg fa-lg fas fa-search"></button>
            </div>
            <div class="col-auto h-100">
                <button id="btnClear" type="button" class="h-100 btn btn-light btn-lg fa-lg fas fa-times"></button>
            </div>
        </form>
    </div>
    <div class="row mt-3">
        <div class="col-12">
            <table id="grid"></table>
        </div>
    </div>
</div>

<div id="modal">
    
</div>

<div class="py-3"></div>

<script type="text/javascript">
        var grid;

        function Remove(e) {
            $.get("@Url.Action("RemoveEquipment")", {
                    equipmentID: e.data.id
                },
                function (data) {
                    $("#modal").html(data);
                    $('#modalConfirmationRemoveEquipment').modal({ backdrop: 'static', keyboard: false });
                });
        }

        function Edit(e) {
            $.get("@Url.Action("EditEquipment")", {
                    equipmentID: e.data.id
                },
                function (data) {
                    $("#modal").html(data);
                    $('#modalEquipmentForm').modal({ backdrop: 'static', keyboard: false });
                    $.validator.unobtrusive.parse("#equipmentForm");
                });
        }

        $(document).ready(function () {
            grid = $('#grid').grid({
                primaryKey: 'EquipmentID',
                dataSource: '@Url.Action("GetEquipments", "Equipment", new { area = "Management" })',
                uiLibrary: 'bootstrap4',
                columns: [
                    { field: 'Name', title: 'Nazwa', sortable: true },
                    { field: 'Brand', title: 'Marka', sortable: true },
                    { field: 'Amount', title: 'Sztuk' },
                    { title: '', field: 'Edit', width: 63, align: 'center', type: 'icon', icon: 'btn btn-primary btn-xs fa-xs fas fa-edit', tooltip: 'Edytuj', events: { 'click': Edit } },
                    { title: '', field: 'Remove', width: 60, align: 'center', type: 'icon', icon: 'btn btn-danger btn-xs fa-xs fas fa-trash-alt', tooltip: 'Usuń', events: { 'click': Remove } }
                ],
                pager: { limit: 10 }
            });

            $('#btnSearch').on('click', function () {
                grid.reload({
                        page: 1,
                        brand: $('#txtBrand').val(),
                        name: $('#txtName').val()
                    });
            });

            $('#btnClear').on('click', function () {
                $('#txtBrand').val('');
                $('#txtName').val('');
                grid.reload({
                    brand: '',
                    name: ''
                });
            });
        });
</script>

FitnessClubApp.Web/Areas/Management/Views/Equipment/_AddEquipmentForm.cshtml
@model FitnessClubApp.Web.Areas.Management.ViewModels.EquipmentFormViewModel

<div class="modal fade" id="modalEquipmentForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Dodaj sprzęt</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            @using (Ajax.BeginForm("AddEquipment", new { },
                new AjaxOptions() { HttpMethod = "POST", OnFailure = "equipmentFormOnFailure", OnSuccess = "$('#modalEquipmentForm').modal('hide'); grid.reload();" }, new { id = "equipmentForm" }))
            {
                <div class="modal-body">

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, "Nazwa")
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control mb-1", placeholder = "Nazwa" } })
                        @Html.ValidationMessageFor(model => model.Name, string.Empty, new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Brand, "Marka")
                        @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control mb-1", placeholder = "Marka" } })
                        @Html.ValidationMessageFor(model => model.Brand, string.Empty, new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Amount, "Liczba sztuk")
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control mb-1", placeholder = "Liczba sztuk" } })
                        @Html.ValidationMessageFor(model => model.Amount, string.Empty, new { @class = "text-danger" })
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Zapisz</button>
                </div>
            }

        </div>
    </div>
</div>

<script>
    function equipmentFormOnFailure(e) {
        $('.modal-backdrop').remove();
        var html = e.responseText;
        $('#modal').html(html);
        $('#modalEquipmentForm').modal({ backdrop: 'static', keyboard: false });
        $.validator.unobtrusive.parse("#equipmentForm");
    }
</script>

FitnessClubApp.Web/Areas/Management/Views/Equipment/_ConfirmationRemoveEquipment.cshtml
@model FitnessClubApp.Model.Equipment

<div class="modal fade" id="modalConfirmationRemoveEquipment" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Usunięcie sprzętu</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            @using (Ajax.BeginForm("ConfirmationRemoveEquipment", new { equipmentID = Model.EquipmentID },
                new AjaxOptions() { HttpMethod = "POST", OnSuccess = "$('#modalConfirmationRemoveEquipment').modal('hide'); grid.reload();" }, new { id = "confirmationRemoveEquipment" }))
            {
                <div class="modal-body">
                    Czy na pewno chcesz usunąć sprzęt <b>@Model.Name (@Model.Brand)</b>?
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Usuń</button>
                </div>
            }

        </div>
    </div>
</div>

FitnessClubApp.Web/Areas/Management/Views/Equipment/_EditEquipmentForm.cshtml
@model FitnessClubApp.Web.Areas.Management.ViewModels.EquipmentFormViewModel

<div class="modal fade" id="modalEquipmentForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edytuj sprzęt</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            @using (Ajax.BeginForm("EditEquipment", new { }, 
                new AjaxOptions() { HttpMethod = "POST", OnFailure = "equipmentFormOnFailure", OnSuccess = "$('#modalEquipmentForm').modal('hide'); grid.reload();" }, new { id = "equipmentForm" } ))
            {
                <div class="modal-body">

                    @Html.HiddenFor(model => model.EquipmentID)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, "Nazwa")
                        @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control mb-1", placeholder = "Nazwa"}})
                        @Html.ValidationMessageFor(model => model.Name, string.Empty, new {@class = "text-danger"})
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Brand, "Marka")
                        @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control mb-1", placeholder = "Marka" } })
                        @Html.ValidationMessageFor(model => model.Brand, string.Empty, new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Amount, "Liczba sztuk")
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control mb-1", placeholder = "Liczba sztuk" } })
                        @Html.ValidationMessageFor(model => model.Amount, string.Empty, new { @class = "text-danger" })
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Zapisz</button>
                </div>
            }

        </div>
    </div>
</div>

<script>
    function equipmentFormOnFailure(e) {
        $('.modal-backdrop').remove();
        var html = e.responseText;
        $('#modal').html(html);
        $('#modalEquipmentForm').modal({ backdrop: 'static', keyboard: false });
        $.validator.unobtrusive.parse("#equipmentForm");
    }
</script>